# Generated by Django 3.1 on 2020-09-19 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cie10', '0001_initial'),
        ('relUnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbNovedades',
            fields=[
                ('id_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('incapacidad', models.CharField(max_length=120)),
                ('prorroga_ini', models.CharField(max_length=120)),
                ('id_novedad_pro', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
                ('estado', models.IntegerField()),
                ('cod_cie', models.ForeignKey(db_column='cod_cie', on_delete=django.db.models.deletion.DO_NOTHING, to='cie10.cie10')),
                ('id_rel_unica', models.ForeignKey(db_column='id_rel_unica', on_delete=django.db.models.deletion.DO_NOTHING, to='relUnica.tbrelunica')),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_reg')),
            ],
            options={
                'db_table': 'tb_novedades',
            },
        ),
    ]
