# Generated by Django 3.1 on 2020-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbSede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('desc_sede', models.CharField(max_length=120)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_sede',
            },
        ),
    ]
