# Generated by Django 3.1 on 2020-09-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCentroCostos',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre_cc', models.CharField(max_length=120)),
                ('estado', models.IntegerField()),
                ('sede', models.ForeignKey(db_column='sede', on_delete=django.db.models.deletion.DO_NOTHING, to='sedes.tbsede')),
            ],
            options={
                'db_table': 'tb_centro_costos',
            },
        ),
    ]
