# Generated by Django 3.1 on 2020-09-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eps', '0001_initial'),
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbEmpleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('doc_empleado', models.CharField(max_length=20, unique=True)),
                ('nombre_empleado', models.CharField(max_length=120)),
                ('estado', models.IntegerField()),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='cargos.tbcargos')),
                ('id_eps', models.ForeignKey(db_column='id_eps', on_delete=django.db.models.deletion.DO_NOTHING, to='eps.tbeps')),
            ],
            options={
                'db_table': 'tb_empleado',
            },
        ),
    ]
