# Generated by Django 3.1 on 2020-09-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('gerente', '0001_initial'),
        ('ejecutivos', '0001_initial'),
        ('empleado', '0001_initial'),
        ('centroCostos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbRelUnica',
            fields=[
                ('id_rel_unica', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('id_cc', models.ForeignKey(db_column='id_cc', on_delete=django.db.models.deletion.DO_NOTHING, to='centroCostos.tbcentrocostos')),
                ('id_ejecutivo', models.ForeignKey(db_column='id_ejecutivo', on_delete=django.db.models.deletion.DO_NOTHING, to='ejecutivos.tbejecutivo')),
                ('id_gerente', models.ForeignKey(db_column='id_gerente', on_delete=django.db.models.deletion.DO_NOTHING, to='gerente.tbgerente')),
                ('id_team', models.ForeignKey(db_column='id_team', on_delete=django.db.models.deletion.DO_NOTHING, to='team.tbteam')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.tbempleado')),
            ],
            options={
                'db_table': 'tb_rel_unica',
            },
        ),
    ]
