# Generated by Django 3.1 on 2020-09-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbGerente',
            fields=[
                ('id_gerente', models.AutoField(primary_key=True, serialize=False)),
                ('doc_gerente', models.CharField(max_length=20, unique=True)),
                ('nombre_gerente', models.CharField(max_length=120)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_gerente',
            },
        ),
    ]
